-- return {
--   "pmizio/typescript-tools.nvim",
--   dependencies = { "nvim-lua/plenary.nvim" },
--   event = { "BufReadPre", "BufNewFile" },
--   ft = { "typescript", "javascript" },
--   opts = {},
-- }
